name: ci

on:
  push:
    branches:
      - main
      - wasm-wip
  pull_request:
    branches:
      - main
      - wasm-wip

permissions:
  contents: read

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          actions-cache-folder: emsdk-cache

      - name: Cache Boost (wasm)
        id: cache-boost
        uses: actions/cache@v4
        with:
          path: deps/boost-wasm/install
          key: boost-wasm-${{ runner.os }}-${{ hashFiles('deps/boost-wasm/build_boost.sh') }}

      - name: Build Boost (if cache miss)
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: bash deps/boost-wasm/build_boost.sh

      - name: Build WASM module
        shell: pwsh
        run: ./build.ps1 -Clean -Jobs 4

      - name: Print toolchain summary
        run: bash scripts/sanity.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm-build-${{ github.run_id }}
          path: |
            build-wasm/slicer.js
            build-wasm/slicer.wasm
            web/public/wasm/slicer.js
            web/public/wasm/slicer.wasm
            build-wasm/CMakeFiles/CMakeOutput.log
            build-wasm/CMakeFiles/CMakeError.log
